# -*- coding: utf-8 -*-
"""model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Rq8PwtvApyxcVFsxmOky4QikUVuh3dr
"""

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, get_scheduler
from torch.optim import AdamW
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from tqdm import tqdm
import pandas as pd
import torch
import torch.nn.functional as F

csv_file = "/content/comments_labels_binary.csv"
df = pd.read_csv(csv_file, encoding="utf-8-sig")
df = df.drop_duplicates(subset=["comment"])
df = df.dropna(subset=["comment", "label"])
df["label"] = df["label"].astype(int)
df.loc[df["label"] > 1, "label"] = 1

train_df, test_df = train_test_split(df, test_size=0.3, random_state=42, stratify=df["label"])
print(f"Train: {len(train_df)}, Test: {len(test_df)}")

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(6, 4))
sns.countplot(x='label', data=df)
plt.title('Phân bố nhãn trong dữ liệu')
plt.xlabel('Nhãn (0: Không độc hại, 1: Độc hại)')
plt.ylabel('Số lượng')
plt.xticks([0, 1], ['Không độc hại', 'Độc hại'])
plt.show()

duplicate_comments = df[df.duplicated(subset=['comment'], keep=False)]
print(f"Số lượng dòng bị trùng lặp: {len(duplicate_comments)}")
print("Các dòng bị trùng lặp:")
display(duplicate_comments.sort_values(by='comment'))
df = df.drop_duplicates(subset=['comment'])

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(6, 4))
sns.countplot(x='label', data=df)
plt.title('Phân bố nhãn trong dữ liệu')
plt.xlabel('Nhãn (0: Không độc hại, 1: Độc hại)')
plt.ylabel('Số lượng')
plt.xticks([0, 1], ['Không độc hại', 'Độc hại'])
plt.show()

from imblearn.over_sampling import RandomOverSampler
from collections import Counter
df['label'] = pd.to_numeric(df['label'], errors='coerce')
df = df.dropna(subset=['label'])
df['label'] = df['label'].astype(int)
print("ok")

toxic_samples = df[df['label'] == 1]['comment'].tolist()
augmented = []
for cmt in toxic_samples[:200]:
    variants = [
        cmt.replace(" ", ""),
        cmt.upper(),
        cmt.replace("u", "w"),
        cmt.replace("ê", "e"),
        cmt + " !!!",
    ]
    for v in variants:
        augmented.append((v, 1))

aug_df = pd.DataFrame(augmented, columns=["comment", "label"])
df = pd.concat([df, aug_df], ignore_index=True)
print("ok")
print("oversampling")
ros = RandomOverSampler(random_state=42)
X_resampled, y_resampled = ros.fit_resample(df[['comment']], df['label'])

df = pd.DataFrame({'comment': X_resampled['comment'], 'label': y_resampled})

print("Ook")
print("Phân bố nhãn:\n", df['label'].value_counts())



train_df, test_df = train_test_split(df, test_size=0.3, random_state=42, stratify=df['label'])
print(f"Train: {len(train_df)}, Test: {len(test_df)}")
print("train:\n", train_df['label'].value_counts())
print("test:\n", test_df['label'].value_counts())

label_counts = df['label'].value_counts()
print(label_counts)
print(label_counts / len(df) * 100)

from transformers import AutoTokenizer
from torch.utils.data import Dataset
import torch

MODEL_NAME = "vinai/phobert-base-v2"
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

class CommentDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_len=128):
        """
        texts: list[str] - danh sách comment
        labels: list[int] - 0 hoặc 1
        """
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = f"hate speech detection: {self.texts[idx]}"

        encoding = self.tokenizer(
            text,
            truncation=True,
            padding="max_length",
            max_length=self.max_len,
            return_tensors="pt"
        )

        return {
            "input_ids": encoding["input_ids"].squeeze(0),
            "attention_mask": encoding["attention_mask"].squeeze(0),
            "labels": torch.tensor(self.labels[idx], dtype=torch.long)
        }

train_df = train_df[train_df['comment'].apply(lambda x: isinstance(x, str))]
test_df = test_df[test_df['comment'].apply(lambda x: isinstance(x, str))]

train_dataset = CommentDataset(train_df['comment'].tolist(), train_df['label'].tolist(), tokenizer)
print("ok")
test_dataset = CommentDataset(test_df['comment'].tolist(), test_df['label'].tolist(), tokenizer)
train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
print("ok")
test_loader = DataLoader(test_dataset, batch_size=16 , shuffle=False)

from transformers import AutoModelForSequenceClassification
# ====== Mô hình ======
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=2)

for name, param in model.named_parameters():
  if "encoder.layer.10" in name or "encoder.layer.11" in name or "classifier" in name:
         param.requires_grad = True
  else:
        param.requires_grad = False
model.to(device)
print("ok")

import torch.nn.functional as F

class FocalLoss(torch.nn.Module):
    def __init__(self, alpha=0.75, gamma=2):
        super(FocalLoss, self).__init__()
        self.alpha = alpha
        self.gamma = gamma

    def forward(self, logits, targets):
        ce_loss = F.cross_entropy(logits, targets, reduction='none')
        pt = torch.exp(-ce_loss)
        focal_loss = (self.alpha * (1 - pt) ** self.gamma * ce_loss).mean()
        return focal_loss


loss_fn = FocalLoss(alpha=0.75, gamma=2.0)
print("ok")

EPOCHS = 10
LEARNING_RATE = 2e-5
optimizer = AdamW(filter(lambda p: p.requires_grad, model.parameters()),
                  lr=LEARNING_RATE, weight_decay=0.01)

num_training_steps = EPOCHS * len(train_loader)
lr_scheduler = get_scheduler(
    "cosine",
    optimizer=optimizer,
    num_warmup_steps=int(0.05 * num_training_steps),
    num_training_steps=num_training_steps,
)

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

best_val_loss = float('inf')
patience = 2
counter = 0
threshold_toxic = 0.7

for epoch in range(EPOCHS):
    print(f"--- EPOCH {epoch+1}/{EPOCHS} ---")
    model.train()
    total_loss = 0
    progress_bar = tqdm(train_loader, desc=f"epoch {epoch+1}")

    for batch in progress_bar:
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)

        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        loss = loss_fn(outputs.logits, labels)
        total_loss += loss.item()

        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()
        lr_scheduler.step()
        optimizer.zero_grad()

        progress_bar.set_postfix({'loss': loss.item()})

    avg_train_loss = total_loss / len(train_loader)
    print(f" Loss huấn luyện trung bình: {avg_train_loss:.4f}")
    # tập val
    model.eval()
    val_loss = 0
    val_preds, val_true = [], []

    with torch.no_grad():
        for batch in test_loader:
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['labels'].to(device)

            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            loss = loss_fn(outputs.logits, labels)
            val_loss += loss.item()

            probs = torch.softmax(outputs.logits, dim=1).cpu().numpy()
            for p in probs:
                toxic_prob = p[1]
                pred_label = 1 if toxic_prob > threshold_toxic else 0
                val_preds.append(pred_label)
            val_true.extend(labels.cpu().numpy())

    avg_val_loss = val_loss / len(test_loader)
    accuracy = accuracy_score(val_true, val_preds)
    precision = precision_score(val_true, val_preds)
    recall = recall_score(val_true, val_preds)
    f1 = f1_score(val_true, val_preds)

    print(f"Valid loss: {avg_val_loss:.4f}")
    print(f" Accuracy: {accuracy:.4f} | Precision: {precision:.4f} | Recall: {recall:.4f} | F1: {f1:.4f}")


    if avg_val_loss < best_val_loss:
        best_val_loss = avg_val_loss
        counter = 0
        model.save_pretrained("saved_model_focal_best")
        tokenizer.save_pretrained("saved_model_focal_best")
        print("lưu")
    else:
        counter += 1
        if counter >= patience:
            print("Dừng sớm")
            break

model = AutoModelForSequenceClassification.from_pretrained("saved_model_focal_best")
tokenizer = AutoTokenizer.from_pretrained("saved_model_focal_best")
model.to(device)

model.eval()
all_probs, all_preds, all_labels = [], [], []
with torch.no_grad():
    for batch in test_loader:
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)

        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        probs = torch.softmax(outputs.logits, dim=1).cpu().numpy()
        preds = (probs[:,1] > 0.4).astype(int)
        all_probs.extend(probs)
        all_preds.extend(preds)
        all_labels.extend(labels.cpu().numpy())

print("\nBáo cáo phân loại:")
print(classification_report(all_labels, all_preds))

print("Ma trận nhầm lẫn:")
print(confusion_matrix(all_labels, all_preds))

from sklearn.metrics import classification_report, confusion_matrix
model.eval()
all_preds, all_labels = [], []
all_probs = []

with torch.no_grad():
    for batch in test_loader:
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)

        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        probs = torch.softmax(outputs.logits, dim=1)
        preds = torch.argmax(probs, dim=1).cpu().numpy()

        all_preds.extend(preds)
        all_labels.extend(labels.cpu().numpy())
        all_probs.extend(probs.cpu().numpy())

print("\n=== Báo cáo phân loại ===")
print(classification_report(all_labels, all_preds, digits=4))

print("\n=== Ma trận nhầm lẫn ===")
print(confusion_matrix(all_labels, all_preds))

def predict_comment(text, threshold=0.5):
      model.eval()
      encoding = tokenizer(
          text,
          truncation=True,
          padding='max_length',
          max_length=128,
          return_tensors='pt'
      ).to(device)

      with torch.no_grad():
          outputs = model(**encoding)
          probs = torch.softmax(outputs.logits, dim=1).cpu().numpy()[0]

      pred_label = 1 if probs[1] > threshold else 0
      return pred_label, probs

comments_to_test = [
    "Ồ, bài viết thật sâu sắc — sâu đến mức tôi phải đào mấy mét mới tìm được ý chính.",
    "Có lẽ bạn là minh chứng sống cho câu “im lặng là vàng” mà ai đó đã bỏ qua.",
    "Thật ngưỡng mộ sự tự tin của bạn khi nói ra điều mà không ai muốn nghe.",
    "Không phải ai cũng có khả năng biến điều đơn giản thành chuyện vô nghĩa như bạn đâu.",
    "Cảm ơn vì đã chia sẻ — giờ tôi đã biết thêm một ví dụ về sự lãng phí thời gian.",
    "Có lẽ bạn nên cân nhắc viết sách dạy người khác đừng bao giờ làm như thế này.",
    "Thật tuyệt khi thấy ai đó dũng cảm thể hiện sự thiếu hiểu biết một cách công khai như vậy.",
    "Tôi chưa bao giờ nghĩ sự kết hợp giữa sự tự tin và thiếu kiến thức lại có thể thú vị đến thế.",
    "Bạn có tài đặc biệt đấy — không phải ai cũng có thể biến mọi cuộc trò chuyện thành chuyện khó chịu.",
    "Xin lỗi, tôi cứ tưởng đây là phần bình luận nghiêm túc chứ không phải tiết mục hài độc thoại."
]

for comment in comments_to_test:
    label, prob = predict_comment(comment, threshold=0.4)
    label_str = "TOXIC" if label == 1 else "NORMAL"
    print(f"Bình luận: \"{comment}\"")
    print(f" Dự đoán: {label_str}, Xác suất = {prob}")
    print("-" * 20)

cm = confusion_matrix(all_labels, all_preds)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Không độc hại', 'Độc hại'], yticklabels=['Không độc hại', 'Độc hại'],
            annot_kws={'size': 12})
plt.xlabel('Dự đoán', fontsize=14)
plt.ylabel('Thực tế', fontsize=14)
plt.title('Ma trận nhầm lẫn', fontsize=16)
plt.tight_layout()
plt.show()